FROM centos:centos7

RUN yum install -y epel-release
RUN yum install -y wget curl zip unzip vim bzip2 net-tools iproute lrzsz nc patch nano \
	lsof rsync bind-utils python-pip gettext git file lftp psmisc psutils \
	gcc-c++ autoconf automake flex-devel cracklib-devel audit-libs-devel libselinux-devel \
	db4-devel libtool flex bison gdb python2-crypto rpm-build rpm-sign expect \
	make cmake ncurses-devel iptables-devel audit-libs-devel audit-libs \
	openssl-devel libpcap-devel gettext-devel libdb-devel libselinux-devel libmnl-devel \
	libcap-ng-devel sharutils libnetfilter_conntrack-devel libnfnetlink-devel glib-devel zlib-devel \
	grubby sysvinit-tools parallel elfutils-libelf-devel
